/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Mystic Steampunk palette (from DESIGN.md)
        surface: "#16130e",
        "surface-dim": "#16130e",
        "surface-bright": "#3d3933",
        "surface-container-lowest": "#110e09",
        "surface-container-low": "#1e1b16",
        "surface-container": "#231f1a",
        "surface-container-high": "#2d2924",
        "surface-container-highest": "#38342e",
        "surface-variant": "#38342e",
        "on-surface": "#e9e1d8",
        "on-surface-variant": "#d1c5b4",
        outline: "#9a8f80",
        "outline-variant": "#4e4639",
        primary: "#e9c176",
        "on-primary": "#412d00",
        "primary-container": "#c5a059",
        "on-primary-container": "#4e3700",
        "primary-fixed": "#ffdea5",
        "primary-fixed-dim": "#e9c176",
        "on-primary-fixed": "#261900",
        "on-primary-fixed-variant": "#5d4201",
        "inverse-primary": "#775a19",
        secondary: "#bac6ec",
        "on-secondary": "#23304e",
        "secondary-container": "#3a4666",
        "on-secondary-container": "#a8b4da",
        tertiary: "#b0c6f9",
        "on-tertiary": "#173059",
        "tertiary-container": "#8fa5d6",
        "on-tertiary-container": "#233a65",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#16130e",
        "on-background": "#e9e1d8",
      },
      fontFamily: {
        serif: ["Newsreader", "ui-serif", "Georgia", "serif"],
        sans: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "title-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
      },
      spacing: {
        unit: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
      },
      boxShadow: {
        "brass-glow": "0 0 15px rgba(233, 193, 118, 0.3)",
        "indigo-glow": "0 0 15px rgba(186, 198, 236, 0.25)",
        "inset-card": "inset 0 1px 0 rgba(255,255,255,0.04), inset 0 -1px 0 rgba(0,0,0,0.5)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 180ms ease-out",
      },
    },
  },
  plugins: [],
};
